### ISSUE TITLE
真实场景的雾天数据合成

### ISSUE THREAD

**Issue by tongchangD** [RQ-Wu/RIDCP_dehazing#10]
近期在网络上收集并看了些图像去雾的代码与论文，发现现今大多数论文多是在刷现有数据集的PSNR或SSIM分数。
而现有数据集多是用去雾机制作的成对数据集或者是利用RGBD数据中D参数合成雾天数据，基本很少有论文真正在真实雾天数据上做的算法。
因为在现实场景中不易构建成对数据集，退化模型也不是完全拟合现实场景。

关于合成数据，我搜集到以下方案：

```python
img = cv2.imread("./1.jpg")  # 需要处理的文件夹
mask_img = img.copy()
# mask_img[:, :] = (144, 128, 112)  # 112, 128, 144 RGB 三种颜色相同时为灰度色彩
mask_img[:, :] = (166, 178, 180)  # 雾的颜色可以调整，看看哪个效果符合自身的需要
A= 0.2 # A 主要控制雾的浓度
image = cv2.addWeighted(img, round(A, 2), mask_img, 1, 0) 
cv2.imwrite("./res0.png", image)
```

光学模型合成雾
```python
img = cv2.imread("./test.png")
img_f = img / 255.0  # 归一化
(row, col, chs) = img.shape
A = 0.5  # 亮度 AA = [0.8 0.85 0.9 0.95 1]
beta = 0.000005  # 雾的浓度 #  [0.1 0.2 0.04 0.06 0.08] ;
beta = 0.005  # 雾的浓度 最高
size = math.sqrt(max(row, col))  # 雾化尺寸，可根据自己的条件进行调节，一般的范围在中心点位置但不是很大，可自己手动设置参数
center = (row // 2, col // 2)  # 雾化中心 就是图片的中心
for j in range(row):
    for l in range(col):
        d = -0.04 * math.sqrt((j - center[0]) ** 2 + (l - center[1]) ** 2) + size
        td = math.exp(-beta * d)
        img_f[j][l][:] = img_f[j][l][:] * td + A * (1 - td)  # 标准光学模型，图片的RGB三通道进行加雾
cv2.imwrite('./dst.png', img_f * 255)
```

请问还有其他比较好的方案，能够利用现实图合成雾图，最终用于去雾吗

**Comment by tongchangD** [comment]
最近在做合成雾，想到了photoshop，请问有利用PS从清晰图上合成雾图，最终用于去雾的吗

**Comment by RQ-Wu** [comment]
不好意思，最近比较忙，一直没时间回issue。

根据模型去合成肯定会有很大的domain gap，如果你能从物理的角度，考虑一些气压问题去把雾的非匀质问题考虑到可能会更好一些，当然这个我不太懂，可能得请教物理专业的同学。另外还可以从摄影的角度考虑光的退化（因为雾天往往是暗光），这个牵扯到RAW图像，相机的ISP等问题，得额外了解一下。

用PS做数据集的话，可能会工作量会比较大，但是简单粗暴。我提供三个思路来减少工作量吧，希望能帮到你。
1. 如果在RIDCP处理后的基础上做PS的话会简单一些。
2. 另外你可以试试model ensemble的方法，之前在水下图像增强上有人这么做，把多个方法处理的结果进行排序，选最好的一个当成gt（WaterNet，TIP2019），还有我之前的工作，把多个图像的排序信息放进去训（Underwater Ranker那篇，我的scholar和homepage都可以找到）。用PS的话你固定好一套p图的pipeline，对不同方法的结果进行人工后处理，然后再排序。
3. 你通过某种方式训一个加权网络（比如基于人工的反馈那种训练方式，这个我胡扯的我不太懂），把多种算法的结果加权成一个更好的结果，然后再PS后处理。

真实图像去雾非常需要好的成对数据集，因为这个对结果的影响是最大的，而且带来的收益比改改网络要直观的多。另外如果能证明合成的数据和真实数据很接近（tSNE、FID等手段），并且在你合成的数据集上的PSNR分数和最终在真实图像上的效果能呈现一个线性关系，那就更好了。我也很希望有相关的工作可以出现。

**Comment by RQ-Wu** [comment]
我看到你在其它issue里说你使用了我们的data但是效果不太好。我个人认为这个数据还算是个即插即用的东西，按理说不会这样，我用MSBDN和Dehamer去训效果也都还可以。是你训太多过拟合了吗，或者网络的学习能力不足？可以加下vx 13645548058讨论一下。

**Comment by tongchangD** [comment]
@RQ-Wu  大佬，感谢您的回复，我没说使用您的数据效果不好，是我用自己的数据按照您的代码进行模型训练，未改任何参数，但效果不太好，有部分原因是我的图效果就不够清晰，色调比较单一。
从数据合成方向上看，效果还算可以，利用了单图的深度信息合成的雾天数据比我搜到的本issues前面提到的两种方案好点。
可能就是传参这块，感觉不太利于 实际部署，故考虑将这个数据合成模块抽出来，单压在其他模型上去试试。


祝好
tongchangD

**Comment by mengxzh15** [comment]
我在我的新论文里对ASM进行了更改，并给出了数学证明，在后面中了后我会共享出数据供你下载。这篇RIDCP里的合成数据方式不可参考，他的做法有N的阶乘种合成方式。我怀疑作者是在审了我去年投的AAAI上题为““ Structural Causal Features Dehazing for Dark Haze”的启发，把数据作的更复杂了，然后和我一样在中间特征进行操作，找了篇域适应特征对齐的方法改了改投的。

**Comment by tongchangD** [comment]
@mengxzh15  您好，那您能展示一下您在真实场景下的去雾效果吗，我现在比较关注的是真实数据的去雾效果，请问在取景较深时的图像上去雾效果如何

**Comment by RQ-Wu** [comment]
> 我在我的新论文里对ASM进行了更改，并给出了数学证明，在后面中了后我会共享出数据供你下载。这篇RIDCP里的合成数据方式不可参考，他的做法有N的阶乘种合成方式。我怀疑作者是在审了我去年投的AAAI上题为““ Structural Causal Features Dehazing for Dark Haze”的启发，把数据作的更复杂了，然后和我一样在中间特征进行操作，找了篇域适应特征对齐的方法改了改投的。

实话实说，我确实审到了这篇论文，而且当时我记得我没给负意见，我在valse还遇见了这篇文章的coauthor，不知道是不是你本人呢。但是这篇文章我是从五月份开始做的，七月底就达到了和最终版差不多的效果，实验的log以及我和老师的聊天记录我都可以公开贴出来，你这样子揣度未免有点不太好？

**Comment by RQ-Wu** [comment]
> 我在我的新论文里对ASM进行了更改，并给出了数学证明，在后面中了后我会共享出数据供你下载。这篇RIDCP里的合成数据方式不可参考，他的做法有N的阶乘种合成方式。我怀疑作者是在审了我去年投的AAAI上题为““ Structural Causal Features Dehazing for Dark Haze”的启发，把数据作的更复杂了，然后和我一样在中间特征进行操作，找了篇域适应特征对齐的方法改了改投的。

我记得是十月份才看的你的文章，试问我有这么快的手速搞出来一篇CVPR吗😂

**Comment by RQ-Wu** [comment]
> 我在我的新论文里对ASM进行了更改，并给出了数学证明，在后面中了后我会共享出数据供你下载。这篇RIDCP里的合成数据方式不可参考，他的做法有N的阶乘种合成方式。我怀疑作者是在审了我去年投的AAAI上题为““ Structural Causal Features Dehazing for Dark Haze”的启发，把数据作的更复杂了，然后和我一样在中间特征进行操作，找了篇域适应特征对齐的方法改了改投的。

您说的这种情况是非常严重的，我也不至于为了一篇文章做这么下流的事情，学术撞车是常有的事情，都是一个领域的researchers本应该友好交流，为何要用恶意揣度呢？下面是我当时和老师的一些聊天以及周报的PPT，时间是8月初，AAAI也没有开始bid，我没有可能看到您的文章
![image](https://github.com/RQ-Wu/RIDCP_dehazing/assets/50363829/f44873d7-058a-42c1-82df-38815bd81cbf)
![image](https://github.com/RQ-Wu/RIDCP_dehazing/assets/50363829/ef49af0d-d92d-4adc-8e88-84485ed46861)

**Comment by RQ-Wu** [comment]
> 我在我的新论文里对ASM进行了更改，并给出了数学证明，在后面中了后我会共享出数据供你下载。这篇RIDCP里的合成数据方式不可参考，他的做法有N的阶乘种合成方式。我怀疑作者是在审了我去年投的AAAI上题为““ Structural Causal Features Dehazing for Dark Haze”的启发，把数据作的更复杂了，然后和我一样在中间特征进行操作，找了篇域适应特征对齐的方法改了改投的。

另外我特地查了一下，你的这篇文章我给的是weak accept，这里是pulic的不方便放图，你可以私聊我给你截review的图。我在看到你的论文之前做出来了实验，看到你的论文之后觉得和我的思路很像觉得不错给了正分，我觉得我没有任何动机和理由做这种事情

**Comment by tongchangD** [comment]
@RQ-Wu  大早上吃了个不似瓜的瓜。大佬晚上都不休息的吗，在国内的话半夜三点还在回邮件，辛苦了。

**Comment by RQ-Wu** [comment]
> @RQ-Wu 大早上吃了个不似瓜的瓜。大佬晚上都不休息的吗，在国内的话半夜三点还在回邮件，辛苦了。

唉，本来都准备睡了，然后突然想起来看看这个repo的issue（最近在准备今年的CVPR一直没时间查看issue，导致累了不少问题）。结果发现这个事，没办法，名誉这个东西还是比较重要的，只能熬夜回复了😂

**Comment by tongchangD** [comment]
@RQ-Wu  今年大佬又有什么新作

**Comment by RQ-Wu** [comment]
> @RQ-Wu 今年大佬又有什么新作

在做视频的diffusion生成方面的工作

**Comment by RQ-Wu** [comment]
此问题已经解决，是一场误会，也希望看到这个issue的同行们不要产生误解

![image](https://github.com/RQ-Wu/RIDCP_dehazing/assets/50363829/a8e3274c-671e-46ab-af87-d7f78b466b04)
