### ISSUE TITLE
我的一些看法

### ISSUE THREAD

**Issue by mengxzh15** [RQ-Wu/RIDCP_dehazing#5]
我觉得这篇文章，最根本的原因还是在于合成了混合的数据，从域泛化的角度考虑，这是做了大量的数据增强。请问，可否把你合成的数据分享出来？我觉得文中所说的先验并不那么重要，根本的还是你合成的最终数据在起作用。

在我看来，DAD的方法依然是众多实验中最有效的。不过DAD的方法也是在合成真实的数据，它是采用判别器来甄别数据的。作者虽然在一些数据看似获得不错的结果，但所对比的NRIQA指标依然太少，尤其是所谓的US。

欢迎反驳。

**Comment by RQ-Wu** [comment]
您好！关于合成用的数据我们已经在readme里放出链接了，训练用的数据是以online的方式进行合成的。我们的先验也能解决合成数据带来的domain gap的问题（比如后面的可控调节部分）。
另外，我们的User Study是以尽可能random的方式进行的（图片的挑选，study过程中显示的顺序等均为随机），我认为我们US指标是可靠可信的，并非是“所谓的US”。后面我们可以整理一下User Study的结果放在git上。这一点我们的代码已经开源了，您也可以进行比较，视觉上的效果是有明显的提升的（DAD很多方法会出现明显红色的伪影），当然这个存在主观成分，您认为DAD效果更好也完全没有关系。

**Comment by Owen718** [comment]
o assess the actual contributions, we can leverage the haze rendering pipeline proposed in the paper and established dehazing networks like AECR-Net and FFA-Net to evaluate the practical impact of the codebook prior. Based on my experience, a well-designed codebook prior can effectively address domain gap issues in low-level tasks. Additionally, there is currently a lack of suitable metrics for objectively evaluating image quality when dehazing real-world images.

**Comment by tongchangD** [comment]
> 
@mengxzh15  您好，请问你现在在去雾项目上用的是何种模型，我利用作者该仓合成了数据，并进行了一些训练，但在我真实数据上效果依旧欠佳，故来此寻求帮助，请问您最终话现在用的哪个模型法。作者的在线数据合成模块也是可以作为插件，扦插到其他的去雾代码中。

祝好
tongchangD

**Comment by mengxzh15** [comment]
> 



> > 
> 
> @mengxzh15 您好，请问你现在在去雾项目上用的是何种模型，我利用作者该仓合成了数据，并进行了一些训练，但在我真实数据上效果依旧欠佳，故来此寻求帮助，请问您最终话现在用的哪个模型法。作者的在线数据合成模块也是可以作为插件，扦插到其他的去雾代码中。
> 
> 祝好 tongchangD

**Comment by mengxzh15** [comment]
> > 
> 
> > > 
> > 
> > 
> > @mengxzh15 您好，请问你现在在去雾项目上用的是何种模型，我利用作者该仓合成了数据，并进行了一些训练，但在我真实数据上效果依旧欠佳，故来此寻求帮助，请问您最终话现在用的哪个模型法。作者的在线数据合成模块也是可以作为插件，扦插到其他的去雾代码中。
> > 祝好 tongchangD

你好，真实数据方面我用的是DCP和域适应去雾domain adpatation dehazing这篇论文。DCP和域适应这里有理论保证，且效果有目共睹。作者合成数据这块，按照作者这个思路，我完全可以把合成数据弄的更复杂些，譬如再加噪声、非均匀情况也加进去、过曝光等，是不是效果更好呢？还有就是这个合成的顺序对效果的影响，这样操作排列组合后可以出一大堆数据集了。这是我反对作者的原因之一，这本质确实是在做数据质量弱化（域泛化里把这叫数据增强)。这样，有相当的多的情况需要考虑进去，您在真实数据上效果欠佳是可以预想到的。通过数据增强，网络自然获得了数据增强的能力，用在一些真实数据上肯定有效果。但是，真实数据情况更复杂，肯定会出现一些合成数据未考虑的情况，在未考虑进的情况中测试，效果必然显著下降。作者合成的这个数据集，是从观察角度出发，仍然缺少理论的证明，我是指结合大气光散射模型ASM的证明。ASM是普遍认可的理想模型，我还没有看到比ASM更合理的模型了。

**Comment by tongchangD** [comment]
@mengxzh15  可能你是对的，我将作者的chm模型啥的都换掉了，直接换成了一个基础的Unet模型，使用相同的数据合成方案，结果是相差无几的。在真实数据上效果都比较差，我现在在尝试使用DAD的方案来合成数据。

**Comment by mengxzh15** [comment]
我想问下，去年的AAAI，你们是否审到过一篇题为Structural Causal Features Dehazing for Dark Haze的文章？

**Comment by mengxzh15** [comment]
您好！我想问下，去年的AAAI，你是否审到或你的导师给过你一篇题为“ Structural Causal Features Dehazing for Dark Haze”的论文？还有去年的CVPR审稿，你们组是否有审到一篇题为“ Deep Causal Invariant Learning for Daytime Dark Haze Removal”的审稿？有就有哈，反正会议都已经过去了，我只是问问。
