### ISSUE TITLE
复现问题

### ISSUE THREAD

**Issue by hdcxqrc** [RQ-Wu/RIDCP_dehazing#6]
你是通过合成数据的psnr结果确定的迭代次数嘛，我总是复现不到你给模型权重的效果，总是差一些。是bachsize的大小的原因么，还是迭代次数或者什么原因

**Comment by RQ-Wu** [comment]
是经验性地确定迭代次数，因为继续训练后在真实数据上并不会有提升。你这个效果是视觉效果差一点还是数字指标差一点？这个问题很难去定位，我看你复现过程中遇到不少问题。这样吧，你加我微信13645548058，咱们细聊吧，git这边很难做到及时回复

**Comment by boohit** [comment]
> 是经验性地确定迭代次数，因为继续训练后在真实数据上并不会有提升。你这个效果是视觉效果差一点还是数字指标差一点？这个问题很难去定位，我看你复现过程中遇到不少问题。这样吧，你加我微信13645548058，咱们细聊吧，git这边很难做到及时回复

作者你人也太好了
