### ISSUE TITLE
About Model Efficiency

### ISSUE THREAD

**Issue by koihoo** [RQ-Wu/RIDCP_dehazing#7]
I did the efficiency test of image dehazing, and the model only got 1.5fps or even lower. Did you test it when doing the experiment?
![image](https://user-images.githubusercontent.com/51013248/235040420-9101face-d140-473d-af8b-62727a440b1c.png)

**Comment by RQ-Wu** [comment]
We did not focus on the efficiency of the model. What is the resolution of the image, please? Also, processing only one image may slow down the average speed due to the large time taken to load the model

**Comment by Owen718** [comment]
It's important to consider the asynchronous nature of the CUDA API and the warm-up time required by your graphics card for optimal performance. For more detailed information on these topics, I recommend consulting both the MIMO-UNet paper and its accompanying code release. @koihoo

**Comment by koihoo** [comment]
> We have not prioritized the efficiency of the model, which is a point that could be further optimized. Can you tell us what the resolution of the image is? Also, as it takes a lot of time to load the model, processing only one image may slow down the average speed

The resolution of the image is 640*438，and I tried to experiment with a whole folder of pictures, including a total of 7 pictures, but the algorithm efficiency is still very low。
![image](https://user-images.githubusercontent.com/51013248/236714355-b599f6dc-56b8-4650-9ced-1d2091a5ebb2.png)

**Comment by RQ-Wu** [comment]
> > We have not prioritized the efficiency of the model, which is a point that could be further optimized. Can you tell us what the resolution of the image is? Also, as it takes a lot of time to load the model, processing only one image may slow down the average speed
> 
> The resolution of the image is 640*438，and I tried to experiment with a whole folder of pictures, including a total of 7 pictures, but the algorithm efficiency is still very low。 ![image](https://user-images.githubusercontent.com/51013248/236714355-b599f6dc-56b8-4650-9ced-1d2091a5ebb2.png)

Thanks for your experiments. We do not particularly focus on the inference speed, since we regard dehazing as a computational photography task. How to make RIDCP more efficient can be valuable future work.
