### ISSUE TITLE
关于生成有雾图像

### ISSUE THREAD

**Issue by cecret3350** [RQ-Wu/RIDCP_dehazing#8]
您好，感谢您如此出色的工作，在阅读完您的论文后我也深受启发。

在阅读合成有雾图像的代码时，我发现transmision map的生成用了以下代码：
`t = np.exp(-(1- img_depth) * 2.0 * beta)`
所以想请教一下这里为什么需要将图像深度`img_depth`变为`(1- img_depth) * 2.0`？

期待您的回复。

**Comment by RQ-Wu** [comment]
因为预测出来的depth是反的，也就是近的接近1，远的接近0，所以我就用1减去了depth map。乘2.0可以算是一个magic number吧，当时试出来会好一些。这个操作就是把depth给scale了一下，因为现有技术只能估计出来相对距离，也许对depth进行动态的scale会更好？

另外分享一下RIDCP与depth map相关的failure case。RIDCP去雾结果中，有的前景上会有一圈虚化的白边，我认为可能是depth map估的不准确造成的，这是一个虽然不大但是值得解决的点。

**Comment by cecret3350** [comment]
感谢您详细的回复与分享，这对我很有帮助。
祝您五一快乐！

**Comment by RQ-Wu** [comment]
节日快乐！
